In [2]:
import numpy as np

a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [6]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
print(Z)


[[1 1]
 [1 1]]


In [7]:

X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out


array([1, 2])

In [8]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)
print(Z)

[[2 1]
 [1 2]]


In [9]:
with open("Example.txt","w") as writefile:
  
  writefile.write("This is line A\n")
  writefile.write("This is line B\n")


In [12]:
with open("Example3.txt","w") as file1:
  
    file1.write("This is line C\n")
